/** Generated by npm run embed:og-assets — do not edit. */
const B64 = '';

function decode(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

let cached: Uint8Array | null = null;

export function getOgFallbackPng(): Uint8Array {
  if (!cached) cached = decode(B64);
  return cached;
}
