import type { MatchStage } from './matchTypes';
import { hotelsSupply } from './data/hotelsSupply';

export type { Match, MatchPhase, MatchStage } from './matchTypes';
export { wc2026Matches as matches } from './wc2026Schedule';

export interface Rental {
  id: number;
  city: string;
  title: string;
  distanceKm: number;
  pricePerNight: number;
  imageUrl: string;
  bedrooms: number;
  rating: number;
  reviews: number;
  host: string;
  whatsapp: string;
  /** Optional: e.g. neighborhood / suburb for display */
  locationDetail?: string;
  /** When set (e.g. 4 strings), card shows these instead of generic beds/distance row */
  amenities?: string[];
}

export type { CarRental } from './data/carRentals';
export { carRentals } from './data/carRentals';
export { CAR_LISTING_ID_START, carCoverImageUrl } from './data/carMedia';

export interface Guide {
  id: number;
  city: string;
  name: string;
  languages: string[];
  specialty: string;
  avatarUrl: string;
  rating: number;
  reviews: number;
  pricePerDay: number;
  whatsapp: string;
  experience: number;
}

export type TicketCategory = 'Category 1' | 'Category 2' | 'Category 3' | 'VIP';

export interface Ticket {
  id: number;
  city: string;
  matchLabel: string;
  stage: MatchStage;
  date: string;
  kickoffTime: string;
  stadium: string;
  homeTeam: string;
  awayTeam: string;
  flag1: string;
  flag2: string;
  category: TicketCategory;
  quantity: number;
  priceEach: number;
  seller: string;
  whatsapp: string;
  verified: boolean;
}


// All 39 tournament days: June 11 → July 19, 2026
export const scheduleDates: string[] = Array.from({ length: 39 }, (_, i) => {
  const d = new Date('2026-06-11');
  d.setDate(d.getDate() + i);
  return d.toISOString().split('T')[0];
});

/** Group-stage window shown on the MVP schedule header: June 11–27, 2026 */
export const groupStageScheduleDates: string[] = Array.from({ length: 17 }, (_, i) => {
  const d = new Date('2026-06-11');
  d.setDate(d.getDate() + i);
  return d.toISOString().split('T')[0];
});

export const cities = [
  { name: 'Mexico City',          country: 'Mexico',  stadium: 'Estadio Azteca',          imageUrl: 'https://images.pexels.com/photos/20891483/pexels-photo-20891483.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 5,  stadiums: 1, landmark: 'Torre Latinoamericana' },
  { name: 'Guadalajara',          country: 'Mexico',  stadium: 'Estadio Akron',            imageUrl: 'https://images.pexels.com/photos/15886901/pexels-photo-15886901.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 4,  stadiums: 1, landmark: 'Catedral de Guadalajara' },
  { name: 'Monterrey',            country: 'Mexico',  stadium: 'Estadio BBVA',             imageUrl: 'https://images.pexels.com/photos/16652814/pexels-photo-16652814.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 4,  stadiums: 1, landmark: 'Cerro de la Silla' },
  { name: 'Toronto',              country: 'Canada',  stadium: 'BMO Field',                imageUrl: 'https://images.pexels.com/photos/28194614/pexels-photo-28194614.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 6,  stadiums: 1, landmark: 'CN Tower' },
  { name: 'Vancouver',            country: 'Canada',  stadium: 'BC Place',                 imageUrl: 'https://images.pexels.com/photos/32864207/pexels-photo-32864207.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 7,  stadiums: 1, landmark: 'Canada Place' },
  { name: 'New York',             country: 'USA',     stadium: 'MetLife Stadium',          imageUrl: 'https://images.pexels.com/photos/2404843/pexels-photo-2404843.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 8,  stadiums: 1, landmark: 'Empire State Building' },
  { name: 'Los Angeles',          country: 'USA',     stadium: 'SoFi Stadium',             imageUrl: 'https://images.pexels.com/photos/1763067/pexels-photo-1763067.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 8,  stadiums: 1, landmark: 'Santa Monica Pier' },
  { name: 'Dallas',               country: 'USA',     stadium: 'AT&T Stadium',             imageUrl: 'https://images.pexels.com/photos/2051002/pexels-photo-2051002.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 9,  stadiums: 1, landmark: 'Downtown Skyline' },
  { name: 'Atlanta',              country: 'USA',     stadium: 'Mercedes-Benz Stadium',    imageUrl: 'https://images.pexels.com/photos/1680140/pexels-photo-1680140.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 8,  stadiums: 1, landmark: 'Centennial Olympic Park' },
  { name: 'Houston',              country: 'USA',     stadium: 'NRG Stadium',              imageUrl: 'https://images.pexels.com/photos/29604620/pexels-photo-29604620.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 7,  stadiums: 1, landmark: 'Downtown Skyline' },
  { name: 'Philadelphia',         country: 'USA',     stadium: 'Lincoln Financial Field',  imageUrl: 'https://images.pexels.com/photos/378570/pexels-photo-378570.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 6,  stadiums: 1, landmark: 'Liberty Bell' },
  { name: 'Kansas City',          country: 'USA',     stadium: 'Arrowhead Stadium',        imageUrl: 'https://images.pexels.com/photos/5660080/pexels-photo-5660080.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 6,  stadiums: 1, landmark: 'Union Station' },
  { name: 'Seattle',              country: 'USA',     stadium: 'Lumen Field',              imageUrl: 'https://images.pexels.com/photos/944636/pexels-photo-944636.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 6,  stadiums: 1, landmark: 'Space Needle' },
  { name: 'San Francisco',        country: 'USA',     stadium: "Levi's Stadium",           imageUrl: 'https://images.pexels.com/photos/208745/pexels-photo-208745.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 6,  stadiums: 1, landmark: 'Golden Gate Bridge' },
  { name: 'Miami',                country: 'USA',     stadium: 'Hard Rock Stadium',        imageUrl: 'https://images.pexels.com/photos/1170686/pexels-photo-1170686.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 7,  stadiums: 1, landmark: 'South Beach' },
  { name: 'Boston',               country: 'USA',     stadium: 'Gillette Stadium',         imageUrl: 'https://images.pexels.com/photos/2097616/pexels-photo-2097616.jpeg?auto=compress&cs=tinysrgb&w=800', matches: 7,  stadiums: 1, landmark: 'Fenway Park Area' },
];

export const rentals: Rental[] = [
  {
    id: 1,
    city: 'Mexico City',
    title: 'Cozy Apt near Azteca',
    distanceKm: 0.8,
    pricePerNight: 95,
    imageUrl: 'https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.9,
    reviews: 87,
    host: 'Carlos M.',
    whatsapp: '525512345678',
  },
  {
    id: 2,
    city: 'Mexico City',
    title: 'Modern Loft - Condesa',
    distanceKm: 3.2,
    pricePerNight: 120,
    imageUrl: 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 1,
    rating: 4.7,
    reviews: 54,
    host: 'Ana R.',
    whatsapp: '525598765432',
  },
  {
    id: 11,
    city: 'Mexico City',
    title: 'Casa Azteca — 200m al Estadio',
    distanceKm: 0.2,
    pricePerNight: 145,
    imageUrl: 'https://images.pexels.com/photos/2079249/pexels-photo-2079249.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 3,
    rating: 5.0,
    reviews: 62,
    host: 'Roberto V.',
    whatsapp: '525534567890',
  },
  {
    id: 12,
    city: 'Mexico City',
    title: 'Dpto Coyoacán — a pasos del Azteca',
    distanceKm: 0.6,
    pricePerNight: 98,
    imageUrl: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.8,
    reviews: 41,
    host: 'Fernanda O.',
    whatsapp: '525545678901',
  },
  {
    id: 13,
    city: 'Mexico City',
    title: 'Suite Estadio Vista — Piso 8',
    distanceKm: 0.4,
    pricePerNight: 175,
    imageUrl: 'https://images.pexels.com/photos/1082326/pexels-photo-1082326.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.9,
    reviews: 29,
    host: 'Luis & Paty',
    whatsapp: '525556789012',
  },
  {
    id: 3,
    city: 'Guadalajara',
    title: 'Casa Tapatía - Zapopan',
    distanceKm: 1.5,
    pricePerNight: 78,
    imageUrl: 'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 3,
    rating: 4.8,
    reviews: 43,
    host: 'Miguel L.',
    whatsapp: '523312345678',
  },
  {
    id: 4,
    city: 'Houston',
    title: 'Downtown Suite - NRG Walk',
    distanceKm: 0.5,
    pricePerNight: 185,
    imageUrl: 'https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.9,
    reviews: 112,
    host: 'James K.',
    whatsapp: '17135551234',
  },
  {
    id: 5,
    city: 'Dallas',
    title: 'Uptown Dallas Penthouse',
    distanceKm: 2.1,
    pricePerNight: 220,
    imageUrl: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 3,
    rating: 4.8,
    reviews: 76,
    host: 'Sarah T.',
    whatsapp: '12145559876',
  },
  {
    id: 6,
    city: 'New York',
    title: 'Brooklyn Brownstone - WC Special',
    distanceKm: 4.5,
    pricePerNight: 310,
    imageUrl: 'https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.6,
    reviews: 201,
    host: 'Emma W.',
    whatsapp: '12125550123',
  },
  {
    id: 7,
    city: 'Philadelphia',
    title: 'Center City Flat - Match Ready',
    distanceKm: 1.2,
    pricePerNight: 175,
    imageUrl: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.8,
    reviews: 63,
    host: 'Rachel B.',
    whatsapp: '12155551234',
  },
  {
    id: 8,
    city: 'Kansas City',
    title: 'Crossroads Loft near Arrowhead',
    distanceKm: 3.0,
    pricePerNight: 145,
    imageUrl: 'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 1,
    rating: 4.7,
    reviews: 38,
    host: 'David M.',
    whatsapp: '18165554321',
  },
  {
    id: 9,
    city: 'Seattle',
    title: 'Capitol Hill Studio - Lumen View',
    distanceKm: 1.8,
    pricePerNight: 195,
    imageUrl: 'https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 1,
    rating: 4.9,
    reviews: 55,
    host: 'Aiko T.',
    whatsapp: '12065556789',
  },
  {
    id: 10,
    city: 'Los Angeles',
    title: 'Hollywood Hills Villa',
    distanceKm: 5.5,
    pricePerNight: 390,
    imageUrl: 'https://images.pexels.com/photos/53610/large-home-residential-house-architecture-53610.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 4,
    rating: 4.9,
    reviews: 134,
    host: 'Sofia L.',
    whatsapp: '13105559012',
  },
  {
    id: 20,
    city: 'Monterrey',
    title: 'Suite Vista Silla — Zona Rosa',
    distanceKm: 2.0,
    pricePerNight: 88,
    imageUrl: 'https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.8,
    reviews: 52,
    host: 'Patricio R.',
    whatsapp: '528112345678',
  },
  {
    id: 21,
    city: 'Toronto',
    title: 'Downtown Toronto - CN Tower Views',
    distanceKm: 1.2,
    pricePerNight: 210,
    imageUrl: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.9,
    reviews: 91,
    host: 'Emily C.',
    whatsapp: '14165551234',
  },
  {
    id: 22,
    city: 'Vancouver',
    title: 'Gastown Loft near BC Place',
    distanceKm: 0.9,
    pricePerNight: 195,
    imageUrl: 'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 1,
    rating: 4.8,
    reviews: 67,
    host: 'Liam W.',
    whatsapp: '16045557890',
  },
  {
    id: 23,
    city: 'Atlanta',
    title: 'Midtown Atlanta — Stadium Walk',
    distanceKm: 1.5,
    pricePerNight: 175,
    imageUrl: 'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.7,
    reviews: 83,
    host: 'Jordan B.',
    whatsapp: '14045559876',
  },
  {
    id: 24,
    city: 'San Francisco',
    title: 'Mission District Flat - Bay Views',
    distanceKm: 3.5,
    pricePerNight: 285,
    imageUrl: 'https://images.pexels.com/photos/2079249/pexels-photo-2079249.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.9,
    reviews: 144,
    host: 'Olivia M.',
    whatsapp: '14155554321',
  },
  {
    id: 25,
    city: 'Miami',
    title: 'South Beach Condo - Ocean Views',
    distanceKm: 5.0,
    pricePerNight: 320,
    imageUrl: 'https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 2,
    rating: 4.9,
    reviews: 188,
    host: 'Isabella V.',
    whatsapp: '13055551234',
  },
  {
    id: 26,
    city: 'Boston',
    title: 'Back Bay Brownstone - Historic',
    distanceKm: 4.2,
    pricePerNight: 240,
    imageUrl: 'https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=800',
    bedrooms: 3,
    rating: 4.8,
    reviews: 72,
    host: 'Patrick O.',
    whatsapp: '16175559012',
  },
];

export const hotels: Rental[] = hotelsSupply;
export const guides: Guide[] = [
  {
    id: 1,
    city: 'Mexico City',
    name: 'Diego Ramirez',
    languages: ['Spanish', 'English', 'Mandarin'],
    specialty: 'Culture & Gastronomy',
    avatarUrl: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 5.0,
    reviews: 143,
    pricePerDay: 80,
    whatsapp: '525511122233',
    experience: 8,
  },
  {
    id: 2,
    city: 'Mexico City',
    name: 'Valeria Cruz',
    languages: ['Spanish', 'French', 'English'],
    specialty: 'History & Nightlife',
    avatarUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 98,
    pricePerDay: 70,
    whatsapp: '525566778899',
    experience: 5,
  },
  {
    id: 3,
    city: 'Guadalajara',
    name: 'Andrés Flores',
    languages: ['Spanish', 'English'],
    specialty: 'Tequila Tours & Traditions',
    avatarUrl: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 67,
    pricePerDay: 60,
    whatsapp: '523344556677',
    experience: 6,
  },
  {
    id: 4,
    city: 'Houston',
    name: 'Maria Santos',
    languages: ['English', 'Spanish', 'Portuguese'],
    specialty: 'Stadium & Fan Zones',
    avatarUrl: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 88,
    pricePerDay: 95,
    whatsapp: '17135559876',
    experience: 4,
  },
  {
    id: 5,
    city: 'Dallas',
    name: 'Tyler Brooks',
    languages: ['English', 'Spanish'],
    specialty: 'BBQ & Sports Culture',
    avatarUrl: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 55,
    pricePerDay: 85,
    whatsapp: '12145553344',
    experience: 3,
  },
  {
    id: 6,
    city: 'New York',
    name: 'Yuna Kim',
    languages: ['Mandarin', 'Spanish', 'English'],
    specialty: 'Urban Exploration & Dining',
    avatarUrl: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 177,
    pricePerDay: 120,
    whatsapp: '12125556688',
    experience: 7,
  },
  {
    id: 7,
    city: 'Philadelphia',
    name: 'Marcus Johnson',
    languages: ['English', 'French'],
    specialty: 'History & Cheesesteak Culture',
    avatarUrl: 'https://images.pexels.com/photos/1300402/pexels-photo-1300402.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 44,
    pricePerDay: 90,
    whatsapp: '12155559988',
    experience: 5,
  },
  {
    id: 8,
    city: 'Kansas City',
    name: 'Lisa Harper',
    languages: ['English', 'Spanish'],
    specialty: 'Jazz & Local Food Scene',
    avatarUrl: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 31,
    pricePerDay: 75,
    whatsapp: '18165554455',
    experience: 4,
  },
  {
    id: 9,
    city: 'Seattle',
    name: 'Kenji Watanabe',
    languages: ['English', 'Japanese'],
    specialty: 'Tech Culture & Nature Trails',
    avatarUrl: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 62,
    pricePerDay: 100,
    whatsapp: '12065557766',
    experience: 6,
  },
  {
    id: 10,
    city: 'Los Angeles',
    name: 'Sofia Reyes',
    languages: ['English', 'Spanish', 'Portuguese'],
    specialty: 'Film Industry & Beach Life',
    avatarUrl: 'https://images.pexels.com/photos/1024311/pexels-photo-1024311.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 5.0,
    reviews: 210,
    pricePerDay: 130,
    whatsapp: '13105553344',
    experience: 9,
  },
  {
    id: 11,
    city: 'Monterrey',
    name: 'Héctor Garza',
    languages: ['Spanish', 'English'],
    specialty: 'Industrial Heritage & Mountains',
    avatarUrl: 'https://images.pexels.com/photos/1300402/pexels-photo-1300402.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 48,
    pricePerDay: 65,
    whatsapp: '528111234567',
    experience: 5,
  },
  {
    id: 12,
    city: 'Toronto',
    name: 'Priya Sharma',
    languages: ['English', 'Hindi', 'French'],
    specialty: 'Multicultural City & Waterfront',
    avatarUrl: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 116,
    pricePerDay: 110,
    whatsapp: '14165556677',
    experience: 7,
  },
  {
    id: 13,
    city: 'Vancouver',
    name: 'Noah Chen',
    languages: ['English', 'Mandarin', 'Cantonese'],
    specialty: 'Mountains, Nature & Asian Culture',
    avatarUrl: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 5.0,
    reviews: 89,
    pricePerDay: 105,
    whatsapp: '16045558899',
    experience: 8,
  },
  {
    id: 14,
    city: 'Atlanta',
    name: 'Darius Washington',
    languages: ['English', 'Spanish'],
    specialty: 'Civil Rights History & Southern Food',
    avatarUrl: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 77,
    pricePerDay: 90,
    whatsapp: '14045551122',
    experience: 6,
  },
  {
    id: 15,
    city: 'San Francisco',
    name: 'Alyssa Park',
    languages: ['English', 'Korean', 'Spanish'],
    specialty: 'Tech Culture & Golden Gate',
    avatarUrl: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 132,
    pricePerDay: 125,
    whatsapp: '14155553344',
    experience: 7,
  },
  {
    id: 16,
    city: 'Miami',
    name: 'Carlos Vega',
    languages: ['English', 'Spanish', 'Portuguese'],
    specialty: 'Beach Life & Latin Culture',
    avatarUrl: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 5.0,
    reviews: 195,
    pricePerDay: 115,
    whatsapp: '13055557788',
    experience: 10,
  },
  {
    id: 17,
    city: 'Boston',
    name: 'Brendan McCarthy',
    languages: ['English', 'French'],
    specialty: 'Colonial History & Sports Culture',
    avatarUrl: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 61,
    pricePerDay: 95,
    whatsapp: '16175559900',
    experience: 5,
  },
];

export const tickets: Ticket[] = [
  {
    id: 1,
    city: 'New York',
    matchLabel: 'Final — MetLife Stadium',
    stage: 'knockout',
    date: '2026-07-19',
    kickoffTime: '18:00',
    stadium: 'MetLife Stadium',
    homeTeam: 'Final W1',
    awayTeam: 'Final W2',
    flag1: '🏆',
    flag2: '🏆',
    category: 'Category 2',
    quantity: 2,
    priceEach: 1800,
    seller: 'Marco F.',
    whatsapp: '12015551234',
    verified: true,
  },
  {
    id: 2,
    city: 'New York',
    matchLabel: 'Final — MetLife Stadium',
    stage: 'knockout',
    date: '2026-07-19',
    kickoffTime: '18:00',
    stadium: 'MetLife Stadium',
    homeTeam: 'Final W1',
    awayTeam: 'Final W2',
    flag1: '🏆',
    flag2: '🏆',
    category: 'VIP',
    quantity: 1,
    priceEach: 4500,
    seller: 'Patricia L.',
    whatsapp: '12015559876',
    verified: true,
  },
  {
    id: 3,
    city: 'Dallas',
    matchLabel: 'Brazil vs Nigeria — Group Stage',
    stage: 'group',
    date: '2026-06-13',
    kickoffTime: '18:00',
    stadium: 'AT&T Stadium',
    homeTeam: 'Brazil',
    awayTeam: 'Nigeria',
    flag1: '🇧🇷',
    flag2: '🇳🇬',
    category: 'Category 1',
    quantity: 4,
    priceEach: 320,
    seller: 'Rafael S.',
    whatsapp: '12145558877',
    verified: true,
  },
  {
    id: 4,
    city: 'Dallas',
    matchLabel: 'Brazil vs Nigeria — Group Stage',
    stage: 'group',
    date: '2026-06-13',
    kickoffTime: '18:00',
    stadium: 'AT&T Stadium',
    homeTeam: 'Brazil',
    awayTeam: 'Nigeria',
    flag1: '🇧🇷',
    flag2: '🇳🇬',
    category: 'Category 3',
    quantity: 2,
    priceEach: 145,
    seller: 'Ana C.',
    whatsapp: '12145552233',
    verified: false,
  },
  {
    id: 5,
    city: 'Los Angeles',
    matchLabel: 'USA vs Bolivia — Group Stage',
    stage: 'group',
    date: '2026-06-12',
    kickoffTime: '20:00',
    stadium: 'SoFi Stadium',
    homeTeam: 'USA',
    awayTeam: 'Bolivia',
    flag1: '🇺🇸',
    flag2: '🇧🇴',
    category: 'Category 1',
    quantity: 2,
    priceEach: 380,
    seller: 'Tyler M.',
    whatsapp: '13105556655',
    verified: true,
  },
  {
    id: 6,
    city: 'Mexico City',
    matchLabel: 'Mexico vs South Africa — Opening Match',
    stage: 'group',
    date: '2026-06-11',
    kickoffTime: '18:00',
    stadium: 'Estadio Azteca',
    homeTeam: 'Mexico',
    awayTeam: 'South Africa',
    flag1: '🇲🇽',
    flag2: '🇿🇦',
    category: 'Category 2',
    quantity: 3,
    priceEach: 280,
    seller: 'Jorge V.',
    whatsapp: '525512345678',
    verified: true,
  },
  {
    id: 7,
    city: 'Houston',
    matchLabel: 'Argentina vs Albania — Group Stage',
    stage: 'group',
    date: '2026-06-13',
    kickoffTime: '15:00',
    stadium: 'NRG Stadium',
    homeTeam: 'Argentina',
    awayTeam: 'Albania',
    flag1: '🇦🇷',
    flag2: '🇦🇱',
    category: 'Category 1',
    quantity: 2,
    priceEach: 420,
    seller: 'Luca P.',
    whatsapp: '17135557788',
    verified: true,
  },
  {
    id: 8,
    city: 'Atlanta',
    matchLabel: 'Brazil vs Ecuador — Group Stage',
    stage: 'group',
    date: '2026-06-14',
    kickoffTime: '18:00',
    stadium: 'Mercedes-Benz Stadium',
    homeTeam: 'Brazil',
    awayTeam: 'Ecuador',
    flag1: '🇧🇷',
    flag2: '🇪🇨',
    category: 'Category 2',
    quantity: 2,
    priceEach: 295,
    seller: 'Bianca O.',
    whatsapp: '14045553322',
    verified: false,
  },
  {
    id: 9,
    city: 'Miami',
    matchLabel: 'USA vs Qatar — Group Stage',
    stage: 'group',
    date: '2026-06-14',
    kickoffTime: '21:00',
    stadium: 'Hard Rock Stadium',
    homeTeam: 'USA',
    awayTeam: 'Qatar',
    flag1: '🇺🇸',
    flag2: '🇶🇦',
    category: 'Category 1',
    quantity: 4,
    priceEach: 350,
    seller: 'James K.',
    whatsapp: '13055551177',
    verified: true,
  },
  {
    id: 10,
    city: 'Vancouver',
    matchLabel: 'Portugal vs Algeria — Group Stage',
    stage: 'group',
    date: '2026-06-17',
    kickoffTime: '18:00',
    stadium: 'BC Place',
    homeTeam: 'Portugal',
    awayTeam: 'Algeria',
    flag1: '🇵🇹',
    flag2: '🇩🇿',
    category: 'Category 2',
    quantity: 2,
    priceEach: 310,
    seller: 'Sofia B.',
    whatsapp: '16045559988',
    verified: true,
  },
  {
    id: 11,
    city: 'Boston',
    matchLabel: 'Germany vs Qatar — Group Stage',
    stage: 'group',
    date: '2026-06-15',
    kickoffTime: '20:00',
    stadium: 'Gillette Stadium',
    homeTeam: 'Germany',
    awayTeam: 'Qatar',
    flag1: '🇩🇪',
    flag2: '🇶🇦',
    category: 'Category 3',
    quantity: 3,
    priceEach: 175,
    seller: 'Kevin H.',
    whatsapp: '16175558877',
    verified: false,
  },
  {
    id: 12,
    city: 'Seattle',
    matchLabel: 'Semifinal — Lumen Field',
    stage: 'knockout',
    date: '2026-07-14',
    kickoffTime: '19:00',
    stadium: 'Lumen Field',
    homeTeam: 'SF W1',
    awayTeam: 'SF W2',
    flag1: '⚽',
    flag2: '⚽',
    category: 'Category 1',
    quantity: 2,
    priceEach: 950,
    seller: 'Emma T.',
    whatsapp: '12065554433',
    verified: true,
  },
];
