/**
 * FIFA World Cup 2026™ — full 104-match schedule (group + knockout).
 * Source: openfootball/worldcup (2026--usa/cup.txt + cup_finals.txt).
 * Venue cities normalized to app listing keys (e.g. New York, San Francisco).
 */
import type { Match } from './matchTypes';

export const wc2026Matches: Match[] = [
  {
    "id": 1,
    "date": "2026-06-11",
    "kickoffTime": "13:00",
    "city": "Mexico City",
    "homeTeam": "Mexico",
    "awayTeam": "South Africa",
    "stadium": "Estadio Azteca",
    "flag1": "🇲🇽",
    "flag2": "🇿🇦",
    "matchNumber": 1,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 2,
    "date": "2026-06-11",
    "kickoffTime": "20:00",
    "city": "Guadalajara",
    "homeTeam": "South Korea",
    "awayTeam": "Czech Republic",
    "stadium": "Estadio Akron",
    "flag1": "🇰🇷",
    "flag2": "🇨🇿",
    "matchNumber": 2,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 3,
    "date": "2026-06-12",
    "kickoffTime": "15:00",
    "city": "Toronto",
    "homeTeam": "Canada",
    "awayTeam": "Bosnia & Herzegovina",
    "stadium": "BMO Field",
    "flag1": "🇨🇦",
    "flag2": "🇧🇦",
    "matchNumber": 7,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 4,
    "date": "2026-06-12",
    "kickoffTime": "18:00",
    "city": "Los Angeles",
    "homeTeam": "USA",
    "awayTeam": "Paraguay",
    "stadium": "SoFi Stadium",
    "flag1": "🇺🇸",
    "flag2": "🇵🇾",
    "matchNumber": 19,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 5,
    "date": "2026-06-13",
    "kickoffTime": "12:00",
    "city": "San Francisco",
    "homeTeam": "Qatar",
    "awayTeam": "Switzerland",
    "stadium": "Levi's Stadium",
    "flag1": "🇶🇦",
    "flag2": "🇨🇭",
    "matchNumber": 8,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 6,
    "date": "2026-06-13",
    "kickoffTime": "18:00",
    "city": "New York",
    "homeTeam": "Brazil",
    "awayTeam": "Morocco",
    "stadium": "MetLife Stadium",
    "flag1": "🇧🇷",
    "flag2": "🇲🇦",
    "matchNumber": 13,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 7,
    "date": "2026-06-13",
    "kickoffTime": "21:00",
    "city": "Boston",
    "homeTeam": "Haiti",
    "awayTeam": "Scotland",
    "stadium": "Gillette Stadium",
    "flag1": "🇭🇹",
    "flag2": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "matchNumber": 14,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 8,
    "date": "2026-06-13",
    "kickoffTime": "21:00",
    "city": "Vancouver",
    "homeTeam": "Australia",
    "awayTeam": "Turkey",
    "stadium": "BC Place",
    "flag1": "🇦🇺",
    "flag2": "🇹🇷",
    "matchNumber": 20,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 9,
    "date": "2026-06-14",
    "kickoffTime": "12:00",
    "city": "Houston",
    "homeTeam": "Germany",
    "awayTeam": "Curaçao",
    "stadium": "NRG Stadium",
    "flag1": "🇩🇪",
    "flag2": "🇨🇼",
    "matchNumber": 25,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 10,
    "date": "2026-06-14",
    "kickoffTime": "15:00",
    "city": "Dallas",
    "homeTeam": "Netherlands",
    "awayTeam": "Japan",
    "stadium": "AT&T Stadium",
    "flag1": "🇳🇱",
    "flag2": "🇯🇵",
    "matchNumber": 31,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 11,
    "date": "2026-06-14",
    "kickoffTime": "19:00",
    "city": "Philadelphia",
    "homeTeam": "Ivory Coast",
    "awayTeam": "Ecuador",
    "stadium": "Lincoln Financial Field",
    "flag1": "🇨🇮",
    "flag2": "🇪🇨",
    "matchNumber": 26,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 12,
    "date": "2026-06-14",
    "kickoffTime": "20:00",
    "city": "Monterrey",
    "homeTeam": "Sweden",
    "awayTeam": "Tunisia",
    "stadium": "Estadio BBVA",
    "flag1": "🇸🇪",
    "flag2": "🇹🇳",
    "matchNumber": 32,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 13,
    "date": "2026-06-15",
    "kickoffTime": "12:00",
    "city": "Seattle",
    "homeTeam": "Belgium",
    "awayTeam": "Egypt",
    "stadium": "Lumen Field",
    "flag1": "🇧🇪",
    "flag2": "🇪🇬",
    "matchNumber": 37,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 14,
    "date": "2026-06-15",
    "kickoffTime": "12:00",
    "city": "Atlanta",
    "homeTeam": "Spain",
    "awayTeam": "Cape Verde",
    "stadium": "Mercedes-Benz Stadium",
    "flag1": "🇪🇸",
    "flag2": "🇨🇻",
    "matchNumber": 43,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 15,
    "date": "2026-06-15",
    "kickoffTime": "18:00",
    "city": "Los Angeles",
    "homeTeam": "Iran",
    "awayTeam": "New Zealand",
    "stadium": "SoFi Stadium",
    "flag1": "🇮🇷",
    "flag2": "🇳🇿",
    "matchNumber": 38,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 16,
    "date": "2026-06-15",
    "kickoffTime": "18:00",
    "city": "Miami",
    "homeTeam": "Saudi Arabia",
    "awayTeam": "Uruguay",
    "stadium": "Hard Rock Stadium",
    "flag1": "🇸🇦",
    "flag2": "🇺🇾",
    "matchNumber": 44,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 17,
    "date": "2026-06-16",
    "kickoffTime": "15:00",
    "city": "New York",
    "homeTeam": "France",
    "awayTeam": "Senegal",
    "stadium": "MetLife Stadium",
    "flag1": "🇫🇷",
    "flag2": "🇸🇳",
    "matchNumber": 49,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 18,
    "date": "2026-06-16",
    "kickoffTime": "18:00",
    "city": "Boston",
    "homeTeam": "Iraq",
    "awayTeam": "Norway",
    "stadium": "Gillette Stadium",
    "flag1": "🇮🇶",
    "flag2": "🇳🇴",
    "matchNumber": 50,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 19,
    "date": "2026-06-16",
    "kickoffTime": "20:00",
    "city": "Kansas City",
    "homeTeam": "Argentina",
    "awayTeam": "Algeria",
    "stadium": "Arrowhead Stadium",
    "flag1": "🇦🇷",
    "flag2": "🇩🇿",
    "matchNumber": 55,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 20,
    "date": "2026-06-16",
    "kickoffTime": "21:00",
    "city": "San Francisco",
    "homeTeam": "Austria",
    "awayTeam": "Jordan",
    "stadium": "Levi's Stadium",
    "flag1": "🇦🇹",
    "flag2": "🇯🇴",
    "matchNumber": 56,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 21,
    "date": "2026-06-17",
    "kickoffTime": "12:00",
    "city": "Houston",
    "homeTeam": "Portugal",
    "awayTeam": "DR Congo",
    "stadium": "NRG Stadium",
    "flag1": "🇵🇹",
    "flag2": "🇨🇩",
    "matchNumber": 61,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 22,
    "date": "2026-06-17",
    "kickoffTime": "15:00",
    "city": "Dallas",
    "homeTeam": "England",
    "awayTeam": "Croatia",
    "stadium": "AT&T Stadium",
    "flag1": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "flag2": "🇭🇷",
    "matchNumber": 67,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 23,
    "date": "2026-06-17",
    "kickoffTime": "19:00",
    "city": "Toronto",
    "homeTeam": "Ghana",
    "awayTeam": "Panama",
    "stadium": "BMO Field",
    "flag1": "🇬🇭",
    "flag2": "🇵🇦",
    "matchNumber": 68,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 24,
    "date": "2026-06-17",
    "kickoffTime": "20:00",
    "city": "Mexico City",
    "homeTeam": "Uzbekistan",
    "awayTeam": "Colombia",
    "stadium": "Estadio Azteca",
    "flag1": "🇺🇿",
    "flag2": "🇨🇴",
    "matchNumber": 62,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 25,
    "date": "2026-06-18",
    "kickoffTime": "12:00",
    "city": "Atlanta",
    "homeTeam": "Czech Republic",
    "awayTeam": "South Africa",
    "stadium": "Mercedes-Benz Stadium",
    "flag1": "🇨🇿",
    "flag2": "🇿🇦",
    "matchNumber": 3,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 26,
    "date": "2026-06-18",
    "kickoffTime": "12:00",
    "city": "Los Angeles",
    "homeTeam": "Switzerland",
    "awayTeam": "Bosnia & Herzegovina",
    "stadium": "SoFi Stadium",
    "flag1": "🇨🇭",
    "flag2": "🇧🇦",
    "matchNumber": 9,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 27,
    "date": "2026-06-18",
    "kickoffTime": "15:00",
    "city": "Vancouver",
    "homeTeam": "Canada",
    "awayTeam": "Qatar",
    "stadium": "BC Place",
    "flag1": "🇨🇦",
    "flag2": "🇶🇦",
    "matchNumber": 10,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 28,
    "date": "2026-06-18",
    "kickoffTime": "19:00",
    "city": "Guadalajara",
    "homeTeam": "Mexico",
    "awayTeam": "South Korea",
    "stadium": "Estadio Akron",
    "flag1": "🇲🇽",
    "flag2": "🇰🇷",
    "matchNumber": 4,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 29,
    "date": "2026-06-19",
    "kickoffTime": "12:00",
    "city": "Seattle",
    "homeTeam": "USA",
    "awayTeam": "Australia",
    "stadium": "Lumen Field",
    "flag1": "🇺🇸",
    "flag2": "🇦🇺",
    "matchNumber": 21,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 30,
    "date": "2026-06-19",
    "kickoffTime": "18:00",
    "city": "Boston",
    "homeTeam": "Scotland",
    "awayTeam": "Morocco",
    "stadium": "Gillette Stadium",
    "flag1": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "flag2": "🇲🇦",
    "matchNumber": 15,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 31,
    "date": "2026-06-19",
    "kickoffTime": "20:00",
    "city": "San Francisco",
    "homeTeam": "Turkey",
    "awayTeam": "Paraguay",
    "stadium": "Levi's Stadium",
    "flag1": "🇹🇷",
    "flag2": "🇵🇾",
    "matchNumber": 22,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 32,
    "date": "2026-06-19",
    "kickoffTime": "20:30",
    "city": "Philadelphia",
    "homeTeam": "Brazil",
    "awayTeam": "Haiti",
    "stadium": "Lincoln Financial Field",
    "flag1": "🇧🇷",
    "flag2": "🇭🇹",
    "matchNumber": 16,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 33,
    "date": "2026-06-20",
    "kickoffTime": "12:00",
    "city": "Houston",
    "homeTeam": "Netherlands",
    "awayTeam": "Sweden",
    "stadium": "NRG Stadium",
    "flag1": "🇳🇱",
    "flag2": "🇸🇪",
    "matchNumber": 33,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 34,
    "date": "2026-06-20",
    "kickoffTime": "16:00",
    "city": "Toronto",
    "homeTeam": "Germany",
    "awayTeam": "Ivory Coast",
    "stadium": "BMO Field",
    "flag1": "🇩🇪",
    "flag2": "🇨🇮",
    "matchNumber": 27,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 35,
    "date": "2026-06-20",
    "kickoffTime": "19:00",
    "city": "Kansas City",
    "homeTeam": "Ecuador",
    "awayTeam": "Curaçao",
    "stadium": "Arrowhead Stadium",
    "flag1": "🇪🇨",
    "flag2": "🇨🇼",
    "matchNumber": 28,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 36,
    "date": "2026-06-20",
    "kickoffTime": "22:00",
    "city": "Monterrey",
    "homeTeam": "Tunisia",
    "awayTeam": "Japan",
    "stadium": "Estadio BBVA",
    "flag1": "🇹🇳",
    "flag2": "🇯🇵",
    "matchNumber": 34,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 37,
    "date": "2026-06-21",
    "kickoffTime": "12:00",
    "city": "Los Angeles",
    "homeTeam": "Belgium",
    "awayTeam": "Iran",
    "stadium": "SoFi Stadium",
    "flag1": "🇧🇪",
    "flag2": "🇮🇷",
    "matchNumber": 39,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 38,
    "date": "2026-06-21",
    "kickoffTime": "12:00",
    "city": "Atlanta",
    "homeTeam": "Spain",
    "awayTeam": "Saudi Arabia",
    "stadium": "Mercedes-Benz Stadium",
    "flag1": "🇪🇸",
    "flag2": "🇸🇦",
    "matchNumber": 45,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 39,
    "date": "2026-06-21",
    "kickoffTime": "18:00",
    "city": "Vancouver",
    "homeTeam": "New Zealand",
    "awayTeam": "Egypt",
    "stadium": "BC Place",
    "flag1": "🇳🇿",
    "flag2": "🇪🇬",
    "matchNumber": 40,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 40,
    "date": "2026-06-21",
    "kickoffTime": "18:00",
    "city": "Miami",
    "homeTeam": "Uruguay",
    "awayTeam": "Cape Verde",
    "stadium": "Hard Rock Stadium",
    "flag1": "🇺🇾",
    "flag2": "🇨🇻",
    "matchNumber": 46,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 41,
    "date": "2026-06-22",
    "kickoffTime": "12:00",
    "city": "Dallas",
    "homeTeam": "Argentina",
    "awayTeam": "Austria",
    "stadium": "AT&T Stadium",
    "flag1": "🇦🇷",
    "flag2": "🇦🇹",
    "matchNumber": 57,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 42,
    "date": "2026-06-22",
    "kickoffTime": "17:00",
    "city": "Philadelphia",
    "homeTeam": "France",
    "awayTeam": "Iraq",
    "stadium": "Lincoln Financial Field",
    "flag1": "🇫🇷",
    "flag2": "🇮🇶",
    "matchNumber": 51,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 43,
    "date": "2026-06-22",
    "kickoffTime": "20:00",
    "city": "New York",
    "homeTeam": "Norway",
    "awayTeam": "Senegal",
    "stadium": "MetLife Stadium",
    "flag1": "🇳🇴",
    "flag2": "🇸🇳",
    "matchNumber": 52,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 44,
    "date": "2026-06-22",
    "kickoffTime": "20:00",
    "city": "San Francisco",
    "homeTeam": "Jordan",
    "awayTeam": "Algeria",
    "stadium": "Levi's Stadium",
    "flag1": "🇯🇴",
    "flag2": "🇩🇿",
    "matchNumber": 58,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 45,
    "date": "2026-06-23",
    "kickoffTime": "12:00",
    "city": "Houston",
    "homeTeam": "Portugal",
    "awayTeam": "Uzbekistan",
    "stadium": "NRG Stadium",
    "flag1": "🇵🇹",
    "flag2": "🇺🇿",
    "matchNumber": 63,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 46,
    "date": "2026-06-23",
    "kickoffTime": "16:00",
    "city": "Boston",
    "homeTeam": "England",
    "awayTeam": "Ghana",
    "stadium": "Gillette Stadium",
    "flag1": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "flag2": "🇬🇭",
    "matchNumber": 69,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 47,
    "date": "2026-06-23",
    "kickoffTime": "19:00",
    "city": "Toronto",
    "homeTeam": "Panama",
    "awayTeam": "Croatia",
    "stadium": "BMO Field",
    "flag1": "🇵🇦",
    "flag2": "🇭🇷",
    "matchNumber": 70,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 48,
    "date": "2026-06-23",
    "kickoffTime": "20:00",
    "city": "Guadalajara",
    "homeTeam": "Colombia",
    "awayTeam": "DR Congo",
    "stadium": "Estadio Akron",
    "flag1": "🇨🇴",
    "flag2": "🇨🇩",
    "matchNumber": 64,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 49,
    "date": "2026-06-24",
    "kickoffTime": "12:00",
    "city": "Vancouver",
    "homeTeam": "Switzerland",
    "awayTeam": "Canada",
    "stadium": "BC Place",
    "flag1": "🇨🇭",
    "flag2": "🇨🇦",
    "matchNumber": 11,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 50,
    "date": "2026-06-24",
    "kickoffTime": "12:00",
    "city": "Seattle",
    "homeTeam": "Bosnia & Herzegovina",
    "awayTeam": "Qatar",
    "stadium": "Lumen Field",
    "flag1": "🇧🇦",
    "flag2": "🇶🇦",
    "matchNumber": 12,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 51,
    "date": "2026-06-24",
    "kickoffTime": "18:00",
    "city": "Miami",
    "homeTeam": "Scotland",
    "awayTeam": "Brazil",
    "stadium": "Hard Rock Stadium",
    "flag1": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "flag2": "🇧🇷",
    "matchNumber": 17,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 52,
    "date": "2026-06-24",
    "kickoffTime": "18:00",
    "city": "Atlanta",
    "homeTeam": "Morocco",
    "awayTeam": "Haiti",
    "stadium": "Mercedes-Benz Stadium",
    "flag1": "🇲🇦",
    "flag2": "🇭🇹",
    "matchNumber": 18,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 53,
    "date": "2026-06-24",
    "kickoffTime": "19:00",
    "city": "Mexico City",
    "homeTeam": "Czech Republic",
    "awayTeam": "Mexico",
    "stadium": "Estadio Azteca",
    "flag1": "🇨🇿",
    "flag2": "🇲🇽",
    "matchNumber": 5,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 54,
    "date": "2026-06-24",
    "kickoffTime": "19:00",
    "city": "Monterrey",
    "homeTeam": "South Africa",
    "awayTeam": "South Korea",
    "stadium": "Estadio BBVA",
    "flag1": "🇿🇦",
    "flag2": "🇰🇷",
    "matchNumber": 6,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 55,
    "date": "2026-06-25",
    "kickoffTime": "16:00",
    "city": "Philadelphia",
    "homeTeam": "Curaçao",
    "awayTeam": "Ivory Coast",
    "stadium": "Lincoln Financial Field",
    "flag1": "🇨🇼",
    "flag2": "🇨🇮",
    "matchNumber": 29,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 56,
    "date": "2026-06-25",
    "kickoffTime": "16:00",
    "city": "New York",
    "homeTeam": "Ecuador",
    "awayTeam": "Germany",
    "stadium": "MetLife Stadium",
    "flag1": "🇪🇨",
    "flag2": "🇩🇪",
    "matchNumber": 30,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 57,
    "date": "2026-06-25",
    "kickoffTime": "18:00",
    "city": "Dallas",
    "homeTeam": "Japan",
    "awayTeam": "Sweden",
    "stadium": "AT&T Stadium",
    "flag1": "🇯🇵",
    "flag2": "🇸🇪",
    "matchNumber": 35,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 58,
    "date": "2026-06-25",
    "kickoffTime": "18:00",
    "city": "Kansas City",
    "homeTeam": "Tunisia",
    "awayTeam": "Netherlands",
    "stadium": "Arrowhead Stadium",
    "flag1": "🇹🇳",
    "flag2": "🇳🇱",
    "matchNumber": 36,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 59,
    "date": "2026-06-25",
    "kickoffTime": "19:00",
    "city": "Los Angeles",
    "homeTeam": "Turkey",
    "awayTeam": "USA",
    "stadium": "SoFi Stadium",
    "flag1": "🇹🇷",
    "flag2": "🇺🇸",
    "matchNumber": 23,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 60,
    "date": "2026-06-25",
    "kickoffTime": "19:00",
    "city": "San Francisco",
    "homeTeam": "Paraguay",
    "awayTeam": "Australia",
    "stadium": "Levi's Stadium",
    "flag1": "🇵🇾",
    "flag2": "🇦🇺",
    "matchNumber": 24,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 61,
    "date": "2026-06-26",
    "kickoffTime": "15:00",
    "city": "Boston",
    "homeTeam": "Norway",
    "awayTeam": "France",
    "stadium": "Gillette Stadium",
    "flag1": "🇳🇴",
    "flag2": "🇫🇷",
    "matchNumber": 53,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 62,
    "date": "2026-06-26",
    "kickoffTime": "15:00",
    "city": "Toronto",
    "homeTeam": "Senegal",
    "awayTeam": "Iraq",
    "stadium": "BMO Field",
    "flag1": "🇸🇳",
    "flag2": "🇮🇶",
    "matchNumber": 54,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 63,
    "date": "2026-06-26",
    "kickoffTime": "18:00",
    "city": "Guadalajara",
    "homeTeam": "Uruguay",
    "awayTeam": "Spain",
    "stadium": "Estadio Akron",
    "flag1": "🇺🇾",
    "flag2": "🇪🇸",
    "matchNumber": 48,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 64,
    "date": "2026-06-26",
    "kickoffTime": "19:00",
    "city": "Houston",
    "homeTeam": "Cape Verde",
    "awayTeam": "Saudi Arabia",
    "stadium": "NRG Stadium",
    "flag1": "🇨🇻",
    "flag2": "🇸🇦",
    "matchNumber": 47,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 65,
    "date": "2026-06-26",
    "kickoffTime": "20:00",
    "city": "Seattle",
    "homeTeam": "Egypt",
    "awayTeam": "Iran",
    "stadium": "Lumen Field",
    "flag1": "🇪🇬",
    "flag2": "🇮🇷",
    "matchNumber": 41,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 66,
    "date": "2026-06-26",
    "kickoffTime": "20:00",
    "city": "Vancouver",
    "homeTeam": "New Zealand",
    "awayTeam": "Belgium",
    "stadium": "BC Place",
    "flag1": "🇳🇿",
    "flag2": "🇧🇪",
    "matchNumber": 42,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 67,
    "date": "2026-06-27",
    "kickoffTime": "17:00",
    "city": "New York",
    "homeTeam": "Panama",
    "awayTeam": "England",
    "stadium": "MetLife Stadium",
    "flag1": "🇵🇦",
    "flag2": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "matchNumber": 71,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 68,
    "date": "2026-06-27",
    "kickoffTime": "17:00",
    "city": "Philadelphia",
    "homeTeam": "Croatia",
    "awayTeam": "Ghana",
    "stadium": "Lincoln Financial Field",
    "flag1": "🇭🇷",
    "flag2": "🇬🇭",
    "matchNumber": 72,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 69,
    "date": "2026-06-27",
    "kickoffTime": "19:30",
    "city": "Miami",
    "homeTeam": "Colombia",
    "awayTeam": "Portugal",
    "stadium": "Hard Rock Stadium",
    "flag1": "🇨🇴",
    "flag2": "🇵🇹",
    "matchNumber": 65,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 70,
    "date": "2026-06-27",
    "kickoffTime": "19:30",
    "city": "Atlanta",
    "homeTeam": "DR Congo",
    "awayTeam": "Uzbekistan",
    "stadium": "Mercedes-Benz Stadium",
    "flag1": "🇨🇩",
    "flag2": "🇺🇿",
    "matchNumber": 66,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 71,
    "date": "2026-06-27",
    "kickoffTime": "21:00",
    "city": "Kansas City",
    "homeTeam": "Algeria",
    "awayTeam": "Austria",
    "stadium": "Arrowhead Stadium",
    "flag1": "🇩🇿",
    "flag2": "🇦🇹",
    "matchNumber": 59,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 72,
    "date": "2026-06-27",
    "kickoffTime": "21:00",
    "city": "Dallas",
    "homeTeam": "Jordan",
    "awayTeam": "Argentina",
    "stadium": "AT&T Stadium",
    "flag1": "🇯🇴",
    "flag2": "🇦🇷",
    "matchNumber": 60,
    "stage": "group",
    "phase": "group"
  },
  {
    "id": 73,
    "date": "2026-06-28",
    "kickoffTime": "12:00",
    "city": "Los Angeles",
    "homeTeam": "2A",
    "awayTeam": "2B",
    "stadium": "SoFi Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 73,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 74,
    "date": "2026-06-29",
    "kickoffTime": "12:00",
    "city": "Houston",
    "homeTeam": "1C",
    "awayTeam": "2F",
    "stadium": "NRG Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 76,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 75,
    "date": "2026-06-29",
    "kickoffTime": "16:30",
    "city": "Boston",
    "homeTeam": "1E",
    "awayTeam": "3A/B/C/D/F",
    "stadium": "Gillette Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 74,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 76,
    "date": "2026-06-29",
    "kickoffTime": "19:00",
    "city": "Monterrey",
    "homeTeam": "1F",
    "awayTeam": "2C",
    "stadium": "Estadio BBVA",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 75,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 77,
    "date": "2026-06-30",
    "kickoffTime": "12:00",
    "city": "Dallas",
    "homeTeam": "2E",
    "awayTeam": "2I",
    "stadium": "AT&T Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 78,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 78,
    "date": "2026-06-30",
    "kickoffTime": "17:00",
    "city": "New York",
    "homeTeam": "1I",
    "awayTeam": "3C/D/F/G/H",
    "stadium": "MetLife Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 77,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 79,
    "date": "2026-06-30",
    "kickoffTime": "19:00",
    "city": "Mexico City",
    "homeTeam": "1A",
    "awayTeam": "3C/E/F/H/I",
    "stadium": "Estadio Azteca",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 79,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 80,
    "date": "2026-07-01",
    "kickoffTime": "12:00",
    "city": "Atlanta",
    "homeTeam": "1L",
    "awayTeam": "3E/H/I/J/K",
    "stadium": "Mercedes-Benz Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 80,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 81,
    "date": "2026-07-01",
    "kickoffTime": "13:00",
    "city": "Seattle",
    "homeTeam": "1G",
    "awayTeam": "3A/E/H/I/J",
    "stadium": "Lumen Field",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 82,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 82,
    "date": "2026-07-01",
    "kickoffTime": "17:00",
    "city": "San Francisco",
    "homeTeam": "1D",
    "awayTeam": "3B/E/F/I/J",
    "stadium": "Levi's Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 81,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 83,
    "date": "2026-07-02",
    "kickoffTime": "12:00",
    "city": "Los Angeles",
    "homeTeam": "1H",
    "awayTeam": "2J",
    "stadium": "SoFi Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 84,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 84,
    "date": "2026-07-02",
    "kickoffTime": "19:00",
    "city": "Toronto",
    "homeTeam": "2K",
    "awayTeam": "2L",
    "stadium": "BMO Field",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 83,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 85,
    "date": "2026-07-02",
    "kickoffTime": "20:00",
    "city": "Vancouver",
    "homeTeam": "1B",
    "awayTeam": "3E/F/G/I/J",
    "stadium": "BC Place",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 85,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 86,
    "date": "2026-07-03",
    "kickoffTime": "13:00",
    "city": "Dallas",
    "homeTeam": "2D",
    "awayTeam": "2G",
    "stadium": "AT&T Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 88,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 87,
    "date": "2026-07-03",
    "kickoffTime": "18:00",
    "city": "Miami",
    "homeTeam": "1J",
    "awayTeam": "2H",
    "stadium": "Hard Rock Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 86,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 88,
    "date": "2026-07-03",
    "kickoffTime": "20:30",
    "city": "Kansas City",
    "homeTeam": "1K",
    "awayTeam": "3D/E/I/J/L",
    "stadium": "Arrowhead Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 87,
    "stage": "knockout",
    "phase": "round_of_32"
  },
  {
    "id": 89,
    "date": "2026-07-04",
    "kickoffTime": "12:00",
    "city": "Houston",
    "homeTeam": "W73",
    "awayTeam": "W75",
    "stadium": "NRG Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 90,
    "stage": "knockout",
    "phase": "round_of_16"
  },
  {
    "id": 90,
    "date": "2026-07-04",
    "kickoffTime": "17:00",
    "city": "Philadelphia",
    "homeTeam": "W74",
    "awayTeam": "W77",
    "stadium": "Lincoln Financial Field",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 89,
    "stage": "knockout",
    "phase": "round_of_16"
  },
  {
    "id": 91,
    "date": "2026-07-05",
    "kickoffTime": "16:00",
    "city": "New York",
    "homeTeam": "W76",
    "awayTeam": "W78",
    "stadium": "MetLife Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 91,
    "stage": "knockout",
    "phase": "round_of_16"
  },
  {
    "id": 92,
    "date": "2026-07-05",
    "kickoffTime": "18:00",
    "city": "Mexico City",
    "homeTeam": "W79",
    "awayTeam": "W80",
    "stadium": "Estadio Azteca",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 92,
    "stage": "knockout",
    "phase": "round_of_16"
  },
  {
    "id": 93,
    "date": "2026-07-06",
    "kickoffTime": "14:00",
    "city": "Dallas",
    "homeTeam": "W83",
    "awayTeam": "W84",
    "stadium": "AT&T Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 93,
    "stage": "knockout",
    "phase": "round_of_16"
  },
  {
    "id": 94,
    "date": "2026-07-06",
    "kickoffTime": "17:00",
    "city": "Seattle",
    "homeTeam": "W81",
    "awayTeam": "W82",
    "stadium": "Lumen Field",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 94,
    "stage": "knockout",
    "phase": "round_of_16"
  },
  {
    "id": 95,
    "date": "2026-07-07",
    "kickoffTime": "12:00",
    "city": "Atlanta",
    "homeTeam": "W86",
    "awayTeam": "W88",
    "stadium": "Mercedes-Benz Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 95,
    "stage": "knockout",
    "phase": "round_of_16"
  },
  {
    "id": 96,
    "date": "2026-07-07",
    "kickoffTime": "13:00",
    "city": "Vancouver",
    "homeTeam": "W85",
    "awayTeam": "W87",
    "stadium": "BC Place",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 96,
    "stage": "knockout",
    "phase": "round_of_16"
  },
  {
    "id": 97,
    "date": "2026-07-09",
    "kickoffTime": "16:00",
    "city": "Boston",
    "homeTeam": "W89",
    "awayTeam": "W90",
    "stadium": "Gillette Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 97,
    "stage": "knockout",
    "phase": "quarter_final"
  },
  {
    "id": 98,
    "date": "2026-07-10",
    "kickoffTime": "12:00",
    "city": "Los Angeles",
    "homeTeam": "W93",
    "awayTeam": "W94",
    "stadium": "SoFi Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 98,
    "stage": "knockout",
    "phase": "quarter_final"
  },
  {
    "id": 99,
    "date": "2026-07-11",
    "kickoffTime": "17:00",
    "city": "Miami",
    "homeTeam": "W91",
    "awayTeam": "W92",
    "stadium": "Hard Rock Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 99,
    "stage": "knockout",
    "phase": "quarter_final"
  },
  {
    "id": 100,
    "date": "2026-07-11",
    "kickoffTime": "20:00",
    "city": "Kansas City",
    "homeTeam": "W95",
    "awayTeam": "W96",
    "stadium": "Arrowhead Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 100,
    "stage": "knockout",
    "phase": "quarter_final"
  },
  {
    "id": 101,
    "date": "2026-07-14",
    "kickoffTime": "14:00",
    "city": "Dallas",
    "homeTeam": "W97",
    "awayTeam": "W98",
    "stadium": "AT&T Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 101,
    "stage": "knockout",
    "phase": "semi_final"
  },
  {
    "id": 102,
    "date": "2026-07-15",
    "kickoffTime": "15:00",
    "city": "Atlanta",
    "homeTeam": "W99",
    "awayTeam": "W100",
    "stadium": "Mercedes-Benz Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 102,
    "stage": "knockout",
    "phase": "semi_final"
  },
  {
    "id": 103,
    "date": "2026-07-18",
    "kickoffTime": "17:00",
    "city": "Miami",
    "homeTeam": "L101",
    "awayTeam": "L102",
    "stadium": "Hard Rock Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 1031,
    "stage": "knockout",
    "phase": "third_place"
  },
  {
    "id": 104,
    "date": "2026-07-19",
    "kickoffTime": "15:00",
    "city": "New York",
    "homeTeam": "W101",
    "awayTeam": "W102",
    "stadium": "MetLife Stadium",
    "flag1": "⚽",
    "flag2": "⚽",
    "matchNumber": 1032,
    "stage": "knockout",
    "phase": "final"
  }
];
